config/routes.rb
Rails.application.routes.draw do
  resources :compensations

  resources :employees

  resources :companies

  devise_for :users

  root 'employees#index'

end

app/models/company.rb
class Company < ActiveRecord::Base
end

app/models/compensation.rb
class Compensation < ActiveRecord::Base
  belongs_to :employee
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :user
  belongs_to :company
  has_many :compensations
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :employee
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name)
    end
end

app/controllers/compensations_controller.rb
class CompensationsController < ApplicationController
  before_action :set_compensation, only: [:show, :edit, :update, :destroy]

  # GET /compensations
  # GET /compensations.json
  def index
    @compensations = Compensation.all
  end

  # GET /compensations/1
  # GET /compensations/1.json
  def show
  end

  # GET /compensations/new
  def new
    @compensation = Compensation.new
    @employees = Employee.all
  end

  # GET /compensations/1/edit
  def edit
    @employee = Employee.all
  end

  # POST /compensations
  # POST /compensations.json
  def create
    @compensation = Compensation.new(compensation_params)

    respond_to do |format|
      if @compensation.save
        format.html { redirect_to @compensation, notice: 'Compensation was successfully created.' }
        format.json { render :show, status: :created, location: @compensation }
      else
        format.html { render :new }
        format.json { render json: @compensation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /compensations/1
  # PATCH/PUT /compensations/1.json
  def update
    respond_to do |format|
      if @compensation.update(compensation_params)
        format.html { redirect_to @compensation, notice: 'Compensation was successfully updated.' }
        format.json { render :show, status: :ok, location: @compensation }
      else
        format.html { render :edit }
        format.json { render json: @compensation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /compensations/1
  # DELETE /compensations/1.json
  def destroy
    @compensation.destroy
    respond_to do |format|
      format.html { redirect_to compensations_url, notice: 'Compensation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_compensation
      @compensation = Compensation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def compensation_params
      params.require(:compensation).permit(:employee_id, :kind, :amount)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:user_id, :company_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/compensations_helper.rb
module CompensationsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Listing companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/compensations/_form.html.erb
<%= form_for(@compensation) do |f| %>
  <% if @compensation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@compensation.errors.count, "error") %> prohibited this compensation from being saved:</h2>

      <ul>
      <% @compensation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :employee_id %><br>
    <%= f.collection_select :employee_id , @employees, :id, :id  %>
  </div>
  <div class="field">
    <%= f.label :kind %><br>
    <%= f.text_field :kind %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/compensations/edit.html.erb
<h1>Editing compensation</h1>

<%= render 'form' %>

<%= link_to 'Show', @compensation %> |
<%= link_to 'Back', compensations_path %>

app/views/compensations/index.html.erb
<h1>Listing compensations</h1>

<table>
  <thead>
    <tr>
      <th>Employee</th>
      <th>Type</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @compensations.each do |compensation| %>
      <tr>
        <td><%= compensation.employee.user.email %></td>
        <td><%= compensation.kind %></td>
        <td><%= compensation.amount %></td>
        <td><%= link_to 'Show', compensation %></td>
        <td><%= link_to 'Edit', edit_compensation_path(compensation) %></td>
        <td><%= link_to 'Destroy', compensation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Compensation', new_compensation_path %>

app/views/compensations/new.html.erb
<h1>New compensation</h1>

<%= render 'form' %>

<%= link_to 'Back', compensations_path %>

app/views/compensations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Employee:</strong>
  <%= @compensation.employee %>
</p>

<p>
  <strong>Type:</strong>
  <%= @compensation.kind %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @compensation.amount %>
</p>

<%= link_to 'Edit', edit_compensation_path(@compensation) %> |
<%= link_to 'Back', compensations_path %>

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.collection_select :user_id , User.all, :id, :email  %>
  </div>
  <div class="field">
    <%= f.label :company_id %><br>
    <%= f.collection_select :company_id , Company.all, :id, :name  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<h1>Listing employees</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Company</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.user.email %></td>
        <td><%= employee.company.name %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @employee.user %>
</p>

<p>
  <strong>Company:</strong>
  <%= @employee.company %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PayrollSystem</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<% if current_user %>
  <%= link_to "sign out" , destroy_user_session_path , method: :delete %>
<% else %>
  <%= link_to "sign in" , new_user_session_path %>
<% end %>

<%= yield %>

</body>
</html>